# docker-compose.yml
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  azurefunc:
    build: .
    depends_on:
      - azurite
    ports:
      - "7071:80"
    volumes:
      - ./:/home/site/wwwroot:rw
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - FUNCTIONS_WORKER_RUNTIME=python
      - AzureWebJobsStorage=UseDevelopmentStorage=true
    stdin_open: true
    tty: true